using System.Net;
using Microsoft.AspNetCore.Mvc;

namespace ProjectManagementSystem.Api.Extensions;

internal static class ControllerBaseExtensions
{
    /// <summary>
    /// 
    /// </summary>
    /// <param name="controller"></param>
    /// <param name="title">
    /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence
    /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
    /// see[RFC7231], Section 3.4).
    /// </param>
    /// <param name="statusCode">
    /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </param>
    /// <param name="detail">
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </param>
    /// <param name="instance">
    /// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    /// </param>
    /// <param name="type">
    /// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
    /// dereferenced, it provide human-readable documentation for the problem type
    /// (e.g., using HTML [W3C.REC-html5-20141028]). When this member is not present, its value is assumed to be
    /// "about:blank".
    /// </param>
    /// <returns></returns>
    public static ObjectResult StatusCode(this ControllerBase controller, HttpStatusCode statusCode, string title, string detail, string instance, string? type = null)
    {
        var problemDetails = new ProblemDetails
        {
            Type = type,
            Title = title,
            Status = (int)statusCode,
            Detail = detail,
            Instance = instance
        };

        return controller.StatusCode((int)statusCode, problemDetails);
    }
}